modify the b2help-print-mcparticles to use the existing example

diff --git a/analysis/tools/b2help-print-mcparticles b/analysis/tools/b2help-print-mcparticles
--- a/analysis/tools/b2help-print-mcparticles
+++ b/analysis/tools/b2help-print-mcparticles
@@ -1,41 +1,33 @@
-#!/usr/bin/env python3
+#!/bin/bash
 
-##########################################################################
-# basf2 (Belle II Analysis Software Framework)                           #
-# Author: The Belle II Collaboration                                     #
-#                                                                        #
-# See git log for contributors and copyright holders.                    #
-# This file is licensed under LGPL-3.0, see LICENSE.md.                  #
-##########################################################################
+print_help() {
+    echo "Usage: $0 [options] -i filename"
+    echo ""
+    echo "This command prints the MCParticles of the input mdst file and output a ntuple including __MCDecayString__."
+    echo "Default output file name is ntuple.root."
+    echo "You can use any basf2's options, e.g. -o, -n, and --skip-events."
+    echo "Specifically, -i is required to select the input mdst file."
+    echo ""
+    echo "Options:"
+    echo "  -i, --input    input mdst file name (required)"
+    echo "  -h, --help     show this this help message and exit"
+    echo ""
+}
 
-"""
-Print the MCParticles of the given mdst file.
-"""
+input_specified=false
+for arg in "$@"; do    
+    if [[ $arg == "-h" || $arg == "--help" ]]; then
+	print_help
+	exit 0
+    elif [[ $arg == "-i" || $arg == "--input" ]]; then
+        input_specified=true
+    fi
+done
 
-import argparse
+if [ "$input_specified" = false ]; then
+    echo "ERROR: You must specify the input file with -i option." >&2
+    print_help
+    exit 1
+fi
 
-import basf2 as b2
-import modularAnalysis as ma
-
-def get_argument_parser():
-    parser = argparse.ArgumentParser(description="""
-This command prints the MCParticles of the given mdst file.
-By default, only the first event is displaied. One can specify the number of events to be displaied by ``-n`` option.
-""")
-    parser.add_argument('filename', help='Input file.')
-    parser.add_argument('-n', '--num_events', type=int, default=1,
-                        help='Number of events to display.')
-    return parser
-
-
-def main(filename, num_events):
-    main = b2.Path()
-    ma.inputMdst(filename, path=main)
-
-    ma.printMCParticles(path=main)
-    b2.process(main, num_events)
-
-if __name__ == "__main__":
-
-    args = get_argument_parser().parse_args()
-    main(args.filename, args.num_events)
+basf2 ${BELLE2_RELEASE_DIR}/analysis/examples/printMCParticleArray.py "$@"
