check_doxygen_warnings: make sure doxygen is installed
git-svn-id: https://belle2.cc.kek.jp/svn/trunk/software@27792 b38c6c8f-bee8-465d-8448-9abe6915d496

diff --git a/framework/tools/check_doxygen_warnings b/framework/tools/check_doxygen_warnings
--- a/framework/tools/check_doxygen_warnings
+++ b/framework/tools/check_doxygen_warnings
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+which doxygen &> /dev/null
+if [ $? -ne 0 ]; then
+    echo "doxygen executable not found. Doxygen must be installed for this script to work"
+    exit 1;
+fi
+
 # check for help argument
 echo $@ | grep -E -- "(^|\\s)(--help|-h)($|\\s)" &>/dev/null
 if [ $? -eq 0 ]; then
